#!/usr/bin/env python3
"""T28 retriever robustness, rebuilt to match the main results table exactly.

The existing T28 (`run_t28_retriever_robustness.py`) is retrieval-stage only and therefore
cannot match the main table, which is measured after the listwise reranker. It also routes
AGS through `verifier.core.evaluate`, a reimplementation that disagrees with the
deployed pipeline by +0.0128 at Recall@200.

This script produces, for a given retriever, a candidates file in the deployed schema, using
the DEPLOYED code path end to end:

  AGS       ags_frozen_grounding.frozen_ags_rankings -> frozen_ags_rerank
            (the same two functions build_frozen_ags_method_record calls), at the frozen
            config, so the only thing that changes is the retriever object.
  one-pass  a single retrieve_candidates over the logged one-pass query.

Nothing is regenerated by an LLM: AGS replays the hypotheses logged in the frozen-AGS trace
and one-pass replays its logged query, so the only new computation is retrieval.

The output is fed to run_fintagging_grounding_baseline.py with --reuse-candidates
--run-rerank, which applies the identical listwise reranker the main table used. Only then
are the numbers comparable to the main table.

COVERAGE-TERM ASYMMETRY, DELIBERATE
    The deployed pipeline runs AGS at w_cov=1.0 (FrozenAgsConfig) and one-pass at w_cov=0.0
    (the TaxonomyRetriever default; only the frozen-AGS path overrides it). Matching the main
    table means reproducing that asymmetry, so this script does. It is a confound for a
    robustness study -- AGS gets the label-coverage term and one-pass does not -- and it is
    recorded in the output manifest rather than silently equalised.

VALIDATION GATE
    Run with --retriever-kind bm25 and the script re-derives the deployed BM25 numbers. They
    must match runs_fintagging_grounding_baseline/*/metrics.json exactly; --assert-matches-bm25
    turns that into a hard failure. Do not spend GPU time on dense/hybrid until it passes.

CPU only. The GPU is needed for the rerank stage that consumes this file.
"""

from __future__ import annotations
# --- resolve local packages regardless of this file's depth in the tree ---
import sys as _sys, pathlib as _pathlib
for _p in _pathlib.Path(__file__).resolve().parents:
    if (_p / "src" / "run_fintagging_grounding_baseline.py").exists():
        _sys.path.insert(0, str(_p / "src"))
        _sys.path.insert(0, str(_p / "analysis"))
        FHS_ROOT = _p
        break
# -------------------------------------------------------------------------

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterator

_PARENT = Path(__file__).resolve().parent.parent
if str(_PARENT) not in sys.path:
    sys.path.insert(0, str(_PARENT))

from ags_frozen_grounding import (  # noqa: E402
    FrozenAgsConfig,
    frozen_ags_rankings,
    frozen_ags_rerank,
)
from ags_symbolic_agreement import DEFAULT_NORMALIZATION_MAP, load_normalization_map  # noqa: E402
from efficiency.dense_index import build_retriever  # noqa: E402
from run_fintagging_grounding_baseline import (  # noqa: E402
    DEFAULT_TAXONOMY_JSONL,
    SCRIPT_DIR,
    Example,
    finalize_candidate_record,
    load_examples,
    load_taxonomy,
    metric_row,
    normalize_tag,
    retrieve_candidates,
)


DEFAULT_TEST_JSONL = FHS_ROOT / "data" / "test" / "test.jsonl"
FROZEN_TRACE = FHS_ROOT / "runs" / "runs_fintagging_grounding_baseline" / "qwen3_32b_frozen_ags" / "bm25_candidates.jsonl"
ONEPASS_TRACE = (
    FHS_ROOT / "runs" / "runs_fintagging_grounding_baseline" / "qwen3_32b_one_pass_grounding" / "bm25_candidates.jsonl"
)
DEFAULT_EMBED_CACHE = FHS_ROOT / "runs" / "runs_ags_t7_t28" / "qwen3_32b" / "dense_embeddings.pt"

# The deployed reference numbers this must reproduce when --retriever-kind bm25.
BM25_REFERENCE = {
    "AGS": FHS_ROOT / "runs" / "runs_fintagging_grounding_baseline" / "qwen3_32b_frozen_ags" / "metrics.json",
    "one_pass": FHS_ROOT / "runs" / "runs_fintagging_grounding_baseline" / "qwen3_32b_one_pass_grounding" / "metrics.json",
}
QUERY_MODE = {"AGS": "frozen_ags", "one_pass": "one_pass_grounding"}
METRICS = ("recall_at_10", "recall_at_50", "recall_at_200", "mrr", "accuracy")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--retriever-kind", choices=("bm25", "dense", "hybrid"), required=True)
    parser.add_argument("--method", choices=("AGS", "one_pass"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--test-jsonl", type=Path, default=DEFAULT_TEST_JSONL)
    parser.add_argument("--taxonomy-jsonl", type=Path, default=DEFAULT_TAXONOMY_JSONL)
    parser.add_argument("--normalization-map", type=Path, default=DEFAULT_NORMALIZATION_MAP)
    parser.add_argument("--embedding-cache", type=Path, default=DEFAULT_EMBED_CACHE)
    parser.add_argument("--dense-model", default="BAAI/bge-large-en-v1.5")
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--rrf-kappa", type=float, default=60.0)
    parser.add_argument("--embed-batch-size", type=int, default=256)
    parser.add_argument("--query-instruction", default=None)
    parser.add_argument(
        "--label-coverage-weight",
        type=float,
        default=None,
        help="Override the deployed asymmetry (AGS 1.0 / one-pass 0.0). Set 1.0 on one-pass to "
        "run the robustness study with the coverage term enabled identically for both methods, "
        "which is what Table 1 reports. Pair it with --onepass-trace and --reference-metrics "
        "pointing at the w_cov=1 run, or the gate compares against the wrong reference.",
    )
    parser.add_argument(
        "--onepass-trace",
        type=Path,
        default=None,
        help="Override the run whose logged one-pass queries are replayed.",
    )
    parser.add_argument(
        "--reference-metrics",
        type=Path,
        default=None,
        help="Override the metrics.json the BM25 gate reproduces.",
    )
    parser.add_argument(
        "--assert-matches-bm25",
        action="store_true",
        help="With --retriever-kind bm25, fail unless the deployed retrieval-stage numbers "
        "are reproduced exactly. This is the gate before any GPU time.",
    )
    parser.add_argument("--tolerance", type=float, default=1e-6)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--log-every", type=int, default=250)
    return parser.parse_args()


def stream_jsonl(path: Path) -> Iterator[dict[str, Any]]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                yield json.loads(line)


def load_logged_hypotheses(path: Path) -> dict[int, list[dict[str, Any]]]:
    """The J=2 structured hypotheses AGS generated, keyed by fact.

    Replayed rather than regenerated so the retriever is the only thing that changes.
    """
    out: dict[int, list[dict[str, Any]]] = {}
    for record in stream_jsonl(path):
        hypotheses = record.get("frozen_ags_hypotheses") or []
        if hypotheses:
            out[int(record["example_idx"])] = hypotheses
    return out


def load_logged_queries(path: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    for record in stream_jsonl(path):
        query = record.get("query")
        if query:
            out[int(record["example_idx"])] = query
    return out


def build_ags_record(
    retriever: Any,
    example: Example,
    hypotheses: list[dict[str, Any]],
    normalization_map: dict[str, Any],
    cfg: FrozenAgsConfig,
) -> dict[str, Any]:
    """Exactly what build_frozen_ags_method_record does, minus the LLM generation step."""
    rounds = frozen_ags_rankings(retriever, example, hypotheses, cfg)
    reranked, _ = frozen_ags_rerank(rounds, example, hypotheses, normalization_map, cfg)
    record = finalize_candidate_record(
        example,
        query_mode=cfg.variant,
        rounds=rounds,
        top_k=cfg.top_k,
        rrf_kappa=cfg.rrf_kappa,
        extra_fields={
            "frozen_ags_config": {
                "variant": cfg.variant,
                "hypotheses": cfg.hypotheses,
                "top_k": cfg.top_k,
                "rrf_kappa": cfg.rrf_kappa,
                "rerank_beta": cfg.rerank_beta,
                "label_coverage_weight": cfg.label_coverage_weight,
                "temperature": cfg.temperature,
                "dual_rendering_modalities": list(cfg.dual_rendering_modalities),
            },
            "frozen_ags_hypotheses": hypotheses,
            "frozen_ags_replayed": True,
        },
    )
    # The reranked pool is the authoritative AGS ranking; finalize_candidate_record's plain
    # sum-RRF is overwritten here exactly as the deployed builder does.
    tags = [candidate["tag"] for candidate in reranked]
    metrics = metric_row(tags, example.gold_tags, (10, 50, cfg.top_k))
    record["candidates"] = reranked
    record["final_candidates"] = reranked
    record["candidate_union_tags"] = tags
    record["retrieval_metrics"] = metrics
    record["gold_rank"] = metrics.get("rank")
    record["search_coverage"] = any(
        normalize_tag(tag) in {normalize_tag(t) for t in tags} for tag in example.gold_tags
    )
    record["total_retrieval_calls"] = len(rounds)
    return record


def build_onepass_record(
    retriever: Any, example: Example, query: str, top_k: int, rrf_kappa: float
) -> dict[str, Any]:
    candidates = retrieve_candidates(retriever, query, example.entity_type, top_k)
    record = finalize_candidate_record(
        example,
        query_mode="one_pass_grounding",
        rounds=[{"round": 1, "query": query, "candidates": candidates}],
        top_k=top_k,
        rrf_kappa=rrf_kappa,
        extra_fields={"one_pass_replayed": True},
    )
    record["query"] = query
    return record


def aggregate(records: list[dict[str, Any]]) -> dict[str, float]:
    n = len(records) or 1
    out: dict[str, float] = {}
    for depth in (10, 50, 200):
        out[f"recall_at_{depth}"] = sum(
            1 for r in records if (r["gold_rank"] or 10**9) <= depth
        ) / n
    out["mrr"] = sum(0.0 if not r["gold_rank"] else 1.0 / r["gold_rank"] for r in records) / n
    out["accuracy"] = sum(1 for r in records if r["gold_rank"] == 1) / n
    return out


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    taxonomy = load_taxonomy(args.taxonomy_jsonl)
    normalization_map = load_normalization_map(args.normalization_map)
    examples = load_examples(args.test_jsonl, limit=args.limit)
    print(f"{len(examples)} facts", flush=True)

    cfg = FrozenAgsConfig()
    # The deployed asymmetry: AGS carries the coverage term, one-pass does not.
    # --label-coverage-weight overrides it, which is how the table is run with the term
    # enabled identically for both methods.
    if args.label_coverage_weight is None:
        w_cov = cfg.label_coverage_weight if args.method == "AGS" else 0.0
    else:
        w_cov = args.label_coverage_weight

    onepass_trace = args.onepass_trace or ONEPASS_TRACE

    retriever = build_retriever(
        args.retriever_kind,
        taxonomy,
        model_name=args.dense_model,
        label_coverage_weight=w_cov,
        rrf_kappa=args.rrf_kappa,
        batch_size=args.embed_batch_size,
        device=args.device,
        query_instruction=args.query_instruction,
        cache_path=args.embedding_cache if args.retriever_kind in ("dense", "hybrid") else None,
    )
    print(f"retriever={args.retriever_kind}  method={args.method}  w_cov={w_cov}", flush=True)

    if args.method == "AGS":
        source = load_logged_hypotheses(FROZEN_TRACE)
        print(f"replaying logged hypotheses for {len(source)} facts", flush=True)
    else:
        source = load_logged_queries(onepass_trace)
        print(f"replaying logged queries from {onepass_trace} for {len(source)} facts", flush=True)

    records: list[dict[str, Any]] = []
    skipped = 0
    with args.output.open("w", encoding="utf-8") as handle:
        for index, example in enumerate(examples, start=1):
            payload = source.get(example.example_idx)
            if not payload:
                skipped += 1
                continue
            if args.method == "AGS":
                record = build_ags_record(retriever, example, payload, normalization_map, cfg)
            else:
                record = build_onepass_record(retriever, example, payload, cfg.top_k, args.rrf_kappa)
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")
            records.append({"gold_rank": record["gold_rank"]})
            if args.log_every and index % args.log_every == 0:
                print(f"  {index}/{len(examples)}", flush=True)

    agg = aggregate(records)
    manifest = {
        "retriever_kind": args.retriever_kind,
        "method": args.method,
        "query_mode": QUERY_MODE[args.method],
        "label_coverage_weight": w_cov,
        "label_coverage_weight_overridden": args.label_coverage_weight is not None,
        "replayed_trace": str(FROZEN_TRACE if args.method == "AGS" else onepass_trace),
        "coverage_asymmetry_note": (
            "The deployed default is AGS at w_cov=1.0 and one-pass at w_cov=0.0, which is a "
            "confound for a robustness comparison. --label-coverage-weight equalises it; this "
            "run used w_cov={:.1f} for {}.".format(w_cov, args.method)
        ),
        "facts_written": len(records),
        "facts_skipped_no_logged_input": skipped,
        "retrieval_stage": {k: round(v, 6) for k, v in agg.items()},
        "output": str(args.output),
        "next_step": (
            "run_fintagging_grounding_baseline.py --reuse-candidates --run-rerank "
            f"--query-mode {QUERY_MODE[args.method]} (GPU); only then is it comparable to the "
            "main table."
        ),
    }

    gate: dict[str, Any] | None = None
    if args.retriever_kind == "bm25" and args.limit is not None:
        # The deployed reference is an aggregate over all 2,509 facts. Comparing a truncated
        # prefix against it is not a reproduction test -- the first facts are a handful of
        # easy tables -- so refuse the comparison rather than report a meaningless mismatch.
        print(
            f"\nBM25 gate SKIPPED: --limit {args.limit} is set, so the rebuilt aggregate covers "
            "a prefix while the deployed reference covers all facts. Re-run without --limit to "
            "evaluate the gate.",
            flush=True,
        )
        manifest["bm25_gate"] = {"skipped_due_to_limit": args.limit}
    elif args.retriever_kind == "bm25":
        reference_path = args.reference_metrics or BM25_REFERENCE[args.method]
        reference = json.loads(reference_path.read_text(encoding="utf-8"))["bm25_retrieval"]
        diffs = {m: round(agg[m] - float(reference[m]), 9) for m in METRICS}
        ok = all(abs(d) <= args.tolerance for d in diffs.values())
        gate = {
            "reference_path": str(reference_path),
            "reference": {m: round(float(reference[m]), 6) for m in METRICS},
            "rebuilt": {m: round(agg[m], 6) for m in METRICS},
            "difference": diffs,
            "matches": ok,
            "tolerance": args.tolerance,
        }
        manifest["bm25_gate"] = gate

    (args.output.parent / f"{args.output.stem}_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print(json.dumps({k: v for k, v in manifest.items() if k != "coverage_asymmetry_note"}, indent=2))
    if gate is not None:
        print("\n=== BM25 REPRODUCTION GATE ===", flush=True)
        for m in METRICS:
            print(
                f"  {m:<14} deployed={gate['reference'][m]:.6f}  rebuilt={gate['rebuilt'][m]:.6f}"
                f"  diff={gate['difference'][m]:+.9f}",
                flush=True,
            )
        print(f"  -> {'MATCH' if gate['matches'] else 'MISMATCH'}", flush=True)
        if args.assert_matches_bm25 and not gate["matches"]:
            raise SystemExit(
                "BM25 reproduction gate FAILED. The rebuilt pipeline does not reproduce the "
                "deployed numbers, so dense/hybrid results from it would not be comparable to "
                "the main table. Do not spend GPU time until this matches."
            )


if __name__ == "__main__":
    main()
